"""Normalized country reference

Revision ID: 345600ec557f
Revises: a228bf0b832a
Create Date: 2024-10-11 10:15:38.052176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "345600ec557f"
down_revision: Union[str, None] = "a228bf0b832a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("artists", sa.Column("country_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fkey_artists_country_id", "artists", "countries", ["country_id"], ["id"]
    )
    op.drop_column("artists", "country")
    op.add_column("labels", sa.Column("country_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fkey_labels_country_id", "labels", "countries", ["country_id"], ["id"]
    )
    op.drop_column("labels", "country")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "labels",
        sa.Column(
            "country", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint("fkey_labels_country_id", "labels", type_="foreignkey")
    op.drop_column("labels", "country_id")
    op.add_column(
        "artists",
        sa.Column(
            "country", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint("fkey_artists_country_id", "artists", type_="foreignkey")
    op.drop_column("artists", "country_id")
    op.drop_table("countries")
    # ### end Alembic commands ###
